---
  - name: Disable mariadb service 
    service:
      name: mysqld
      state: stopped
      enabled: no
    register: disable_maria
  - debug:
      var: disable_maria.state

  - name: Disable firewall
    firewalld:
      port: 3306/tcp 
      state: disabled
      permanent: yes
