---
  - name: upload public key of vagrant to new user - enable password less auth
    authorized_key:
      user: "{{ item.key }}"
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    loop: "{{ lookup('dict', users) }}"
    when: (item.value.grp == "sre" and ansible_hostname == item.value.sys) or (item.value.grp == "devops" and ansible_hostname == item.value.sys) or (item.value.grp == "engmgr")
    register: ssh_keys
