---
  - name: Install httpd 
    yum:
      name: httpd
      state: latest
    notify: restart httpd
    register: install_httpd
  - debug:
      var: install_httpd

  - name: httpd configure firewall rules
    firewalld:
      port: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    with_items:
      - 80/tcp
      - 443/tcp
    register: httpd_firewall
  - debug:
      var: httpd_firewall
