---
  - name: gzip all files
    archive:
      path: /srv/backup
      dest: /srv
      format: gz
      remove: no
    register: gzip
    when: inventory_hostname == "node1" or inventory_hostname == "node2"
  - debug:
      var: gzip

