---
# handlers file for mariadb_httpd
  - name: restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
    register: restart_httpd
  - debug:
      var: restart_httpd
  
  - name: restart mariadb
    service:
      name: mariadb
      state: restarted
      enabled: yes
    register: restart_mariadb
  - debug:
      var: restart_mariadb
    
